export const PERMISSIONS = {
  BOOK_VIEW: 'BOOK_VIEW',
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  SUB_CATEGORY_VIEW: 'SUB_CATEGORY_VIEW',
  SUB_CATEGORY_CREATE: 'SUB_CATEGORY_CREATE',
  SUB_CATEGORY_UPDATE: 'SUB_CATEGORY_UPDATE',
  SUB_CATEGORY_DELETE: 'SUB_CATEGORY_DELETE',
  LOAN_VIEW: 'LOAN_VIEW',
  USER_VIEW: 'USER_VIEW',
  USER_UPDATE_ROLE: 'USER_UPDATE_ROLE',
  USER_UPDATE_STATUS: 'USER_UPDATE_STATUS',
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  PERMISSION_MANAGE: 'PERMISSION_MANAGE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export function hasPermission(permissions: string[] | undefined, permission: Permission): boolean {
  return !!permissions?.includes(permission);
}